### ISSUE TITLE
Prog. Personaje

### ISSUE THREAD

**Issue by Payoyo12** [IES-Rafael-Alberti/GameOff2024RogueLab#1]

**Comment by Payoyo12** [comment]
el día 06/11/2024 realice el script del movimiento del personaje, que no pueda moverse al interactuar con algo

**Comment by Payoyo12** [comment]
añadido de opción a pausar el juego, en cullo caso no podrás moverte al jugador.
creación de opcionManager.

**Comment by Payoyo12** [comment]
puse un escenario para comprobar la colision y funciona correctamente

**Comment by Payoyo12** [comment]
cambio de sitio de script y función para actualizar el estado del vsyng

**Comment by mlanbay** [comment]
Bug Report: El movimiento diagonal suma ambos vectores sin normalizase.
Traduccion a cristiano: Que se mueve mas rapido en diagonal que recto, consultar con DISEÑO si el movimiento en diagonal esta en sus planes

**Comment by Payoyo12** [comment]
creacion de diferentes shaders que podremos usar mas adelante

**Comment by Payoyo12** [comment]
se han corregido shaders y se a intentado aplicar a la escenas pero hay problemas con eso y averiguar como hacerlo que no se ha conseguido

**Comment by Payoyo12** [comment]
report: hay que cambiar el que no se mueva en diagonal

**Comment by Payoyo12** [comment]
shader de sangre funcional en "escena" y personaje ya no se mueve en diagonal .
tuve problemas con los shader pero me ayudo javy
