### ISSUE TITLE
Implementar puzle foto

### ISSUE THREAD

**Issue by Payoyo12** [IES-Rafael-Alberti/GameOff2024RogueLab#5]

**Comment by Payoyo12** [comment]
he empezado con en codigo de la estanteria pero tengo que parar, estoy en casa i me necesitan. ya puede provarse falta que el jugador reciba el objeto para que al interactuar haga el puzle

**Comment by mlanbay** [comment]
El codigo que has hecho es el referente a un trigger y ya esta implemetado de otra forma, el puzzle al que se refiere el issue deberia ser el canvas que aparece por encima para mostrar diferentes objetos y que al final cuando obtengas todas (las flags activadas) pues que puedas arrastrar y soltar las partes de la foto

**Comment by Payoyo12** [comment]
ya cree el script encargado de arrastrar un objeto y funciona correctamente
